In [3]:
import numpy as np

In [98]:
%autosave 100

Autosaving every 100 seconds


In [8]:
#vector - scalar
x=np.array([1,2,3])
c=5


print('plus: {}'.format(x+c))  

plus: [6 7 8]


In [12]:
# vector-vector
y=np.array([1,3,5])
z=np.array([2,9,20])
print('plus: {}'.format(y+z)) 


plus: [ 3 12 25]


------------------
#### NUMPY INDEXING
2D: array[raw idx, col idx]


In [4]:

w= np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(w[0,0])


1


------------

#### NUMPY SLICING

- **[a:b]** a$^{th}$ to (b-1)$^{th}$
- **[  :b]** 0$^{th}$ to (b-1)$^{th}$
- **[a:  ]** a$^{th}$ to end
- **[ : ]** all 


In [9]:
print('w[0:2]=')
print(w[0:2])
print('\nw[0:2]=')
print(w[:2])

w[0:2]=
[[1 2 3 4]
 [5 6 7 8]]

w[0:2]=
[[1 2 3 4]
 [5 6 7 8]]


In [12]:
w[:3, 2:4]

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])

In [13]:
w[:, 2:4]

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])

#### ARRAY BROADCASTING
: Numpy가 연산을 진행하는 특수 방식

- M x N (calculate) M x 1 <br>
  1D matrix M >> M*N matrix <br><br>
 $\begin{pmatrix}1&2&3\\4&5&6\\7&8&9\\ \end{pmatrix}$ x 
 $\begin{pmatrix}a\\b\\c\\ \end{pmatrix}$
 ----> $\begin{pmatrix}1&2&3\\4&5&6\\7&8&9\\ \end{pmatrix}$ x 
 <span style='color: dodgerblue'>$\begin{pmatrix}a&a&a\\b&b&b\\c&c&c\\ \end{pmatrix}$</span> 
 =  $\begin{pmatrix}1a&2a&3a\\4b&5b&6b\\7c&8c&9c\\ \end{pmatrix}$<br><br>
- M x N (calculate) 1 x N <br>
  1D matrix N >> M*N matrix <br><br>
 $\begin{pmatrix}1&2&3\\4&5&6\\7&8&9\\ \end{pmatrix}$ x 
 $\begin{pmatrix}a&b&c\\ \end{pmatrix}$ 
 ----> $\begin{pmatrix}1&2&3\\4&5&6\\7&8&9\\ \end{pmatrix}$ x
 <span style='color: dodgerblue'>$\begin{pmatrix}a&b&c\\a&b&c\\a&b&c\\ \end{pmatrix}$</span>
 =  $\begin{pmatrix}1a&2b&3c\\4a&5b&6c\\7a&8b&9c\\ \end{pmatrix}$<br><br>
 - M x 1 (calculate) 1 x N <br>
  :두 matrix의 사이즈 맞춰 M X N, M x N의 2D처럼 <span style='color: dodgerblue'> "Broadcasting" </span> & 연산

In [28]:
#. m by n, m by 1
a= np.array([[1,2,3],[4,5,6],[7,8,9]])
x= np.array([0,1,0])

x= x[:, None]


print(a+x)

[[1 2 3]
 [5 6 7]
 [7 8 9]]


In [29]:
#2. m by n, 1 by n 
y= np.array([0,1,-1])
print(a * y)

[[ 0  2 -3]
 [ 0  5 -6]
 [ 0  8 -9]]


In [37]:
# m by 1, 1 by n 
t= np.array([1,2,3])
t= t[:, None]
u= np.array([2,0,-2])

print('t= ', t)
print('\nu= ',u)
print('\nt+u= ',t+u)

t=  [[1]
 [2]
 [3]]

u=  [ 2  0 -2]

t+u=  [[ 3  1 -1]
 [ 4  2  0]
 [ 5  3  1]]


#### LINEAR ALGEBRA WITH NUMPY
- 0-vector: **np.zeros([dim])**
- 1-vector: **np.ones([dim])**
- diagonal matrix: **np.diag((main_diagonal))** <span style='color:gray'>(main diagonal 외 0, main_diagoanl: tuple)</span>
- identity matrix (항등행렬, 대각행렬) : **np.eye()** <span style='color:gray'>(main diagonal=1, else 0)</span>


In [42]:
print(np.zeros([3,3]))
print(np.zeros([2,2,4]))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [41]:
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [45]:
np.diag((1,1,1))

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [47]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])